# Generated by Django 5.1.2 on 2024-11-09 00:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_management', '0001_initial'),
        ('ticket_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='org_management.organization'),
            preserve_default=False,
        ),
    ]
