# Generated by Django 5.1.2 on 2024-10-30 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management', '0002_remove_ticket_column_ticket_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
