# Generated by Django 5.1.2 on 2024-11-10 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('org_management', '0001_initial'),
        ('ticket_management', '0002_ticket_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.CreateModel(
            name='TicketNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('org', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_sequence', to='org_management.organization')),
            ],
        ),
        migrations.DeleteModel(
            name='TicketComment',
        ),
    ]
