# Generated by Django 5.1.2 on 2024-10-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket_management', '0003_ticket_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='mark_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
