# Generated by Django 5.1.2 on 2024-10-29 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org_management', '0002_organization_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='user',
        ),
    ]
