# Generated by Django 5.1.2 on 2024-11-11 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='is_site_owner',
        ),
        migrations.AddField(
            model_name='appuser',
            name='role',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Site Owner'), (2, 'Site Admin'), (3, 'Manager'), (4, 'Base Employee'), (5, 'Full Employee')], default=2),
        ),
    ]
