# Generated by Django 5.1.2 on 2024-11-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_remove_appuser_is_site_owner_appuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='current_active_project',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
