# Generated by Django 5.1.2 on 2024-10-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0002_appuser_is_active_appuser_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_site_owner',
            field=models.BooleanField(default=False),
        ),
    ]
