# Generated by Django 5.1.2 on 2024-10-29 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0003_appuser_is_site_owner'),
        ('org_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='organizations',
            field=models.ManyToManyField(default=None, related_name='users', to='org_management.organization'),
        ),
    ]
