# Generated by Django 5.1.2 on 2024-10-29 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0004_appuser_organizations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='organizations',
        ),
    ]
