# Generated by Django 5.1.2 on 2024-10-30 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_user', '0006_appuser_org'),
        ('org_management', '0003_remove_organization_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='org',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='org_management.organization'),
        ),
    ]
